"""Schema inicial

Revision ID: 9673dec865ca
Revises: 
Create Date: 2026-09-05 23:59:42.974029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9673dec865ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('abbr', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('unities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('unities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unities_code'), ['code'], unique=True)

    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('computer_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['room_categories.id'], ),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_id', 'code', name='uq_classroom_unity_code')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_unity_id'), ['unity_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_id', 'code', name='uq_course_unity_code')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_unity_id'), ['unity_id'], unique=False)

    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_id', 'date', name='uq_holiday_unity_date')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('idx_holiday_active', ['date', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_unity_id'), ['unity_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('registration', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('function', sa.String(length=120), nullable=True),
    sa.Column('profile_type', sa.String(length=20), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_registration'), ['registration'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_id', 'code', name='uq_subject_unity_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_unity_id'), ['unity_id'], unique=False)

    op.create_table('teacher_base_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('month_start', sa.String(length=7), nullable=False),
    sa.Column('month_end', sa.String(length=7), nullable=False),
    sa.Column('budget_code', sa.Integer(), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('weekly_workload', sa.Integer(), nullable=False),
    sa.Column('monthly_hour', sa.Integer(), nullable=True),
    sa.Column('semester_hour', sa.Integer(), nullable=True),
    sa.Column('accountable_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('term_generated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_base_pay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_base_pay_unity_id'), ['unity_id'], unique=False)

    op.create_table('teacher_overtime_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('teaching_level', sa.String(length=50), nullable=False),
    sa.Column('weekly_workload', sa.Integer(), nullable=False),
    sa.Column('hourly_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_code', sa.String(length=18), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('multiple_dates', sa.String(length=255), nullable=True),
    sa.Column('justification', sa.String(length=100), nullable=True),
    sa.Column('month_base', sa.String(length=7), nullable=False),
    sa.Column('accountable_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accountable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_overtime_pay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_overtime_pay_unity_id'), ['unity_id'], unique=False)

    op.create_table('technical_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_sheets_unity_id'), ['unity_id'], unique=False)

    op.create_table('kitchen_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('technical_sheet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipments', sa.Text(), nullable=True),
    sa.Column('utensils', sa.Text(), nullable=True),
    sa.Column('prep_time', sa.String(length=255), nullable=True),
    sa.Column('yield_info', sa.String(length=255), nullable=True),
    sa.Column('steps_text', sa.Text(), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['technical_sheet_id'], ['technical_sheets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kitchen_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kitchen_recipes_unity_id'), ['unity_id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('idx_reservation_conflict', ['classroom_id', 'date', 'status'], unique=False)
        batch_op.create_index('idx_reservation_teacher_date', ['teacher_id', 'date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_unity_id'), ['unity_id'], unique=False)

    op.create_table('teacher_additive_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_release_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('unity_id', sa.Integer(), nullable=True),
    sa.Column('month_start', sa.String(length=7), nullable=False),
    sa.Column('month_end', sa.String(length=7), nullable=False),
    sa.Column('additional_hour', sa.Integer(), nullable=False),
    sa.Column('monthly_hour', sa.Integer(), nullable=True),
    sa.Column('semester_hour', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('accountable_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('term_generated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountable_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['base_release_id'], ['teacher_base_pay.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unity_id'], ['unities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_additive_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_additive_payment_unity_id'), ['unity_id'], unique=False)

    op.create_table('kitchen_preparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['kitchen_recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kitchen_preparations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kitchen_preparations_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('kitchen_recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preparation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_raw', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['preparation_id'], ['kitchen_preparations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kitchen_recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kitchen_recipe_ingredients_preparation_id'), ['preparation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kitchen_recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kitchen_recipe_ingredients_preparation_id'))

    op.drop_table('kitchen_recipe_ingredients')
    with op.batch_alter_table('kitchen_preparations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kitchen_preparations_recipe_id'))

    op.drop_table('kitchen_preparations')
    with op.batch_alter_table('teacher_additive_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_additive_payment_unity_id'))

    op.drop_table('teacher_additive_payment')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_unity_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_date'))
        batch_op.drop_index('idx_reservation_teacher_date')
        batch_op.drop_index('idx_reservation_conflict')

    op.drop_table('reservations')
    with op.batch_alter_table('kitchen_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kitchen_recipes_unity_id'))

    op.drop_table('kitchen_recipes')
    with op.batch_alter_table('technical_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_sheets_unity_id'))

    op.drop_table('technical_sheets')
    with op.batch_alter_table('teacher_overtime_pay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_overtime_pay_unity_id'))

    op.drop_table('teacher_overtime_pay')
    with op.batch_alter_table('teacher_base_pay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_base_pay_unity_id'))

    op.drop_table('teacher_base_pay')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_unity_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_registration'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_unity_id'))
        batch_op.drop_index(batch_op.f('ix_holidays_date'))
        batch_op.drop_index('idx_holiday_active')

    op.drop_table('holidays')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_unity_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_unity_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_code'))

    op.drop_table('classrooms')
    with op.batch_alter_table('unities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unities_code'))

    op.drop_table('unities')
    op.drop_table('room_categories')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
